generator:
  employee:
    hire_date:  # hired before $(random between min and max) days
      min: 0
      max: 90
    dept_id:    # belongs to random department between min and max
      min: 1
      max: 10
    salary:     # has salary between min and max
      min: 10000.0
      max: 50000.0